### ISSUE TITLE
Error when install theme

### ISSUE THREAD

**Issue by thanhlh90it** [adamsiwiec/hexagon#1]
I get error message : when call "sudo hexagon -t ppoffice/hexo-theme-icarus"
hexagon-cli/node_modules/async/dist/async.js:3686
        task(rest(function (err, args) {

**Comment by adamsiwiec** [comment]
Let me run a test and see if I can reproduce this

**Comment by adamsiwiec** [comment]
Can you give me more of that error, because that doesn't look like all of it

**Comment by adamsiwiec** [comment]
I have fixed this issue, upgrade hexagon to 0.3.0 with `npm install -g hexagon-cli` and things should be good to go! 👍
