### ISSUE TITLE
Feature Request: Install themes/plugins as a git submodules

### ISSUE THREAD

**Issue by json2d** [adamsiwiec/hexagon#4]
Hey, since its expected that you would use git to repo your entire hexo project, it would be great if this tool could automatically setup installed themes/plugins as submodules to workaround the repo-inside-a-repo conflict.  Some more info here:

[https://git-scm.com/docs/git-submodule](https://git-scm.com/docs/git-submodule)

What do you think?

**Comment by adamsiwiec** [comment]
I think that is a great idea @bitstrider! Unfortunately, I am not well versed in git submodules. I would love it if you could submit a pull request if you feel like you have a good understanding of submodules. I will try to do some more research over the days and see if I can implement it! Thanks

**Comment by json2d** [comment]
Sure i'll take shot at it.  `simple-git` supports the submodule commands in their API, so it should be fairly straight-forward 👍
