### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by poldiwa** [adamsiwiec/hexagon#5]
I'm a newbie, and I don't know where and how to start on contributing to the project.

**Comment by adamsiwiec** [comment]
How about writing some unit tests with mocha? Can you handle that @poldiwa ?

**Comment by poldiwa** [comment]
@adamsiwiec could you make a starting point, so I can have a reference? I don't have experience in making tests. But I would really like to learn. I don't know how to test CLI apps and google won't really help much.

**Comment by adamsiwiec** [comment]
I am going to close this until I hear more info from you. Cheers!
