### ISSUE TITLE
[BUG] Yarn usage

### ISSUE THREAD

**Issue by HaoZeke** [adamsiwiec/hexagon#6]
I installed hexagon with yarn, however, I now get errors 

```bash
hexa -p hexo-admin
                                   
⬡                             
                              
✖ Installing packages         
⚠️ Uh Oh! Something went wrong check npm-debug.log for more info
```
I also cannot find the npm-debug.log

The same command works with yarn

```bash
yarn add hexo-admin
```

**Comment by adamsiwiec** [comment]
I will add a yarn check to use yarn (if available). I think that should solve your problem

**Comment by adamsiwiec** [comment]
Check out v1.2.0. Let me know if you still have trouble.
