### ISSUE TITLE
Command taking just the first character of the argument

### ISSUE THREAD

**Issue by ComputersMania** [adamsiwiec/hexagon#7]
I can't install anything, it does this:
hexagon -t klugjo/hexo-theme-alpha-dust

⬡

⠋ Cloning themes
Git#then is deprecated after version 1.72 and will be removed in version 2.x
Please switch to using Git#exec to run arbitrary functions as part of the command chain.

⠧ Cloning themesCloning into 'k'...
remote: Not Found
fatal: repository 'https://github.com/k/' not found

⠼ Cloning themes^C

**Comment by adamsiwiec** [comment]
I will take a look and send out a new release as soon as possible.

**Comment by adamsiwiec** [comment]
Try 1.1.4 and if there is still any trouble let me know. Cheers 🎉

**Comment by ComputersMania** [comment]
Yep now it's working thanks
